-- Update ActivityLog activity_type check constraint
ALTER TABLE activity_logs DROP CONSTRAINT IF EXISTS activity_logs_activity_type_check;

ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_activity_type_check 
CHECK (activity_type IN (
    'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_LOGIN', 'USER_LOGOUT', 'PASSWORD_CHANGED',
    'STUDENT_ENROLLED', 'STUDENT_UPDATED', 'STUDENT_TRANSFERRED', 'STUDENT_GRADUATED', 'STUDENT_SUSPENDED',
    'STAFF_HIRED', 'STAFF_UPDATED', 'STAFF_TERMINATED', 'STAFF_PROMOTED',
    'PARENT_ADDED', 'PARENT_UPDATED', 'PARENT_REMOVED',
    'CLASS_CREATED', 'CLASS_UPDATED', 'SUBJECT_CREATED', 'SUBJECT_UPDATED', 
    'ASSIGNMENT_CREATED', 'ASSIGNMENT_SUBMITTED', 'GRADE_ENTERED', 
    'EXAM_CREATED', 'EXAM_SCHEDULED', 'ATTENDANCE',
    'FEE_CREATED', 'PAYMENT_RECEIVED', 'PAYMENT_FAILED', 'INVOICE_GENERATED', 'DISCOUNT_APPLIED',
    'NOTIFICATION_SENT', 'MESSAGE_SENT', 'SMS_SENT', 'WHATSAPP_SENT', 'INTERNAL_MESSAGE_SENT', 'ANNOUNCEMENT_POSTED',
    'SYSTEM_BACKUP', 'SYSTEM_MAINTENANCE', 'DATA_EXPORT', 'DATA_IMPORT',
    'SECURITY_ALERT', 'PERMISSION_CHANGED', 'ROLE_ASSIGNED', 'ROLE_REMOVED',
    'PARENT_STUDENT_LINKED', 'PARENT_STUDENT_UNLINKED',
    'CLASS_TEACHER_ASSIGNED', 'CLASS_TEACHER_REMOVED',
    'SUBJECT_TEACHER_ASSIGNED', 'SUBJECT_TEACHER_REMOVED'
));
