package com.haneef._school.service

import com.haneef._school.entity.School
import com.haneef._school.entity.Settlement
import org.springframework.stereotype.Service
import java.awt.Color
import java.awt.Font
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import java.io.ByteArrayOutputStream
import java.math.BigDecimal
import java.time.format.DateTimeFormatter
import javax.imageio.ImageIO

@Service
class InvoiceService {

    fun generateInvoiceImage(
        settlement: Settlement, 
        school: School, 
        totalBill: BigDecimal,
        settledBill: BigDecimal,
        outstandingBill: BigDecimal
    ): ByteArray {
        val width = 800
        val height = 1000
        val image = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
        val g2d = image.createGraphics()

        // Set rendering hints for better text quality
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON)

        // Background
        g2d.color = Color.WHITE
        g2d.fillRect(0, 0, width, height)

        // Header Background
        g2d.color = Color(0, 51, 102) // Dark Blue
        g2d.fillRect(0, 0, width, 150)

        // School Name
        g2d.color = Color.WHITE
        g2d.font = Font("SansSerif", Font.BOLD, 40)
        g2d.drawString("4School/" + (school.name ?: "School Name"), 50, 90)

        // Invoice Title
        g2d.color = Color(0, 51, 102)
        g2d.font = Font("SansSerif", Font.BOLD, 30)
        g2d.drawString("PAYMENT RECEIPT", 50, 220)

        // Details Section
        g2d.color = Color.BLACK
        g2d.font = Font("SansSerif", Font.PLAIN, 20)
        
        val startY = 300
        val lineHeight = 50
        val labelX = 50
        val valueX = 300

        // Date
        g2d.drawString("Date:", labelX, startY)
        g2d.drawString(settlement.createdAt.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")), valueX, startY)

        // Reference
        g2d.drawString("Reference:", labelX, startY + lineHeight)
        g2d.drawString(settlement.reference, valueX, startY + lineHeight)

        // Session
        g2d.drawString("Session:", labelX, startY + lineHeight * 2)
        g2d.drawString(settlement.academicSession?.sessionName ?: "N/A", valueX, startY + lineHeight * 2)

        // Term
        g2d.drawString("Term:", labelX, startY + lineHeight * 3)
        g2d.drawString(settlement.term?.termName ?: "N/A", valueX, startY + lineHeight * 3)

        // Amount Paid
        g2d.font = Font("SansSerif", Font.BOLD, 20)
        g2d.drawString("Amount Paid:", labelX, startY + lineHeight * 4)
        g2d.drawString("${settlement.currency} ${settlement.amount}", valueX, startY + lineHeight * 4)

        // Financial Summary Section
        val summaryY = startY + lineHeight * 6
        g2d.color = Color(0, 51, 102)
        g2d.drawString("FINANCIAL SUMMARY", labelX, summaryY)
        g2d.drawLine(labelX, summaryY + 5, width - 50, summaryY + 5)
        
        g2d.color = Color.BLACK
        g2d.font = Font("SansSerif", Font.PLAIN, 20)
        
        // Total Bill
        g2d.drawString("Total Bill:", labelX, summaryY + lineHeight)
        g2d.drawString("${settlement.currency} $totalBill", valueX, summaryY + lineHeight)
        
        // Settled Bill
        g2d.drawString("Settled Bill:", labelX, summaryY + lineHeight * 2)
        g2d.drawString("${settlement.currency} $settledBill", valueX, summaryY + lineHeight * 2)
        
        // Outstanding Bill
        g2d.font = Font("SansSerif", Font.BOLD, 20)
        g2d.color = Color.RED
        g2d.drawString("Outstanding:", labelX, summaryY + lineHeight * 3)
        g2d.drawString("${settlement.currency} $outstandingBill", valueX, summaryY + lineHeight * 3)

        // Footer
        g2d.color = Color.GRAY
        g2d.font = Font("SansSerif", Font.ITALIC, 16)
        g2d.drawString("Thank you for your payment.", 50, 850)
        g2d.drawString("Generated by 4School Management System", 50, 880)

        g2d.dispose()

        val baos = ByteArrayOutputStream()
        ImageIO.write(image, "png", baos)
        return baos.toByteArray()
    }
}
