-- Create table global_subjects if not exists
CREATE TABLE IF NOT EXISTS global_subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(255) UNIQUE,
    min_grade_level INTEGER NOT NULL DEFAULT 1,
    max_grade_level INTEGER NOT NULL DEFAULT 12,
    category VARCHAR(255),
    is_core BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Insert subjects
INSERT INTO global_subjects (name, min_grade_level, max_grade_level, is_core, created_at, updated_at) VALUES
('Upholstery', 10, 12, FALSE, NOW(), NOW()),
('Visual Art', 10, 12, FALSE, NOW(), NOW()),
('Welding And Fabrication', 10, 12, FALSE, NOW(), NOW()),
('Woodwork', 10, 12, FALSE, NOW(), NOW()),
('Yoruba Language', 10, 12, FALSE, NOW(), NOW()),
('Leather Goods', 10, 12, FALSE, NOW(), NOW()),
('Literature-in-English', 10, 12, FALSE, NOW(), NOW()),
('Machine Woodworking', 10, 12, FALSE, NOW(), NOW()),
('Marketing', 10, 12, FALSE, NOW(), NOW()),
('Metal Work', 10, 12, FALSE, NOW(), NOW()),
('Mining', 10, 12, FALSE, NOW(), NOW()),
('Music', 10, 12, FALSE, NOW(), NOW()),
('Office Practice', 10, 12, FALSE, NOW(), NOW()),
('Painting And Decoration', 10, 12, FALSE, NOW(), NOW()),
('Photography', 10, 12, FALSE, NOW(), NOW()),
('Physical Education', 10, 12, FALSE, NOW(), NOW()),
('Physics', 10, 12, TRUE, NOW(), NOW()),
('Plumbing And Pipe Fitting', 10, 12, FALSE, NOW(), NOW()),
('Printing Craft Practice', 10, 12, FALSE, NOW(), NOW()),
('Radio Television and Electrical Work', 10, 12, FALSE, NOW(), NOW()),
('Radio Television And Repairs', 10, 12, FALSE, NOW(), NOW()),
('Salesmanship', 10, 12, FALSE, NOW(), NOW()),
('Store Keeping', 10, 12, FALSE, NOW(), NOW()),
('Store Management', 10, 12, FALSE, NOW(), NOW()),
('Technical Drawings', 10, 12, FALSE, NOW(), NOW()),
('Textile trade', 10, 12, FALSE, NOW(), NOW()),
('Tie And Dye Craft', 10, 12, FALSE, NOW(), NOW()),
('Tourism', 10, 12, FALSE, NOW(), NOW()),
('Cosmetology', 10, 12, FALSE, NOW(), NOW()),
('Data Processing', 10, 12, FALSE, NOW(), NOW()),
('Dyeing And Bleaching', 10, 12, FALSE, NOW(), NOW()),
('Economics', 10, 12, TRUE, NOW(), NOW()),
('Electrical Installation And Maintenance Work', 10, 12, FALSE, NOW(), NOW()),
('English Language', 10, 12, TRUE, NOW(), NOW()),
('Financial Accounting', 10, 12, FALSE, NOW(), NOW()),
('Fisheries', 10, 12, FALSE, NOW(), NOW()),
('Foods & Nutrition', 10, 12, FALSE, NOW(), NOW()),
('French Language', 10, 12, FALSE, NOW(), NOW()),
('Furniture Making', 10, 12, FALSE, NOW(), NOW()),
('Further Mathematics', 10, 12, FALSE, NOW(), NOW()),
('Garment Making', 10, 12, FALSE, NOW(), NOW()),
('General Mathematics', 10, 12, TRUE, NOW(), NOW()),
('Geography', 10, 12, FALSE, NOW(), NOW()),
('Government', 10, 12, FALSE, NOW(), NOW()),
('GSM Maintenance And Repairs', 10, 12, FALSE, NOW(), NOW()),
('Health Education', 10, 12, FALSE, NOW(), NOW()),
('History', 10, 12, FALSE, NOW(), NOW()),
('Home Management', 10, 12, FALSE, NOW(), NOW()),
('Igbo Language', 10, 12, FALSE, NOW(), NOW()),
('Insurance', 10, 12, FALSE, NOW(), NOW()),
('Islamic Studies', 10, 12, FALSE, NOW(), NOW()),
('Keyboarding', 10, 12, FALSE, NOW(), NOW()),
('Agricultural Science', 10, 12, TRUE, NOW(), NOW()),
('Air Conditioning And Refrigeration', 10, 12, FALSE, NOW(), NOW()),
('Animal Husbandary', 10, 12, FALSE, NOW(), NOW()),
('Arabic', 10, 12, FALSE, NOW(), NOW()),
('Auto body repair And Spray painting', 10, 12, FALSE, NOW(), NOW()),
('Auto Electrical Works', 10, 12, FALSE, NOW(), NOW()),
('Auto Mechanical Works', 10, 12, FALSE, NOW(), NOW()),
('Auto Mechanics', 10, 12, FALSE, NOW(), NOW()),
('Automobile Parts Merchandising', 10, 12, FALSE, NOW(), NOW()),
('Autopart Merchandizing', 10, 12, FALSE, NOW(), NOW()),
('Basic Electricity', 10, 12, FALSE, NOW(), NOW()),
('Basic Electronics', 10, 12, FALSE, NOW(), NOW()),
('Biology', 10, 12, TRUE, NOW(), NOW()),
('Block laying, Brick laying & Concrete Works', 10, 12, FALSE, NOW(), NOW()),
('Book Keeping', 10, 12, FALSE, NOW(), NOW()),
('Building Construction', 10, 12, FALSE, NOW(), NOW()),
('Carpentary And Joinery', 10, 12, FALSE, NOW(), NOW()),
('Catering and Craft Practice', 10, 12, FALSE, NOW(), NOW()),
('Chemistry', 10, 12, TRUE, NOW(), NOW()),
('Christian Religious Studies', 10, 12, FALSE, NOW(), NOW()),
('Civic Education (Senior)', 10, 12, TRUE, NOW(), NOW()),
('Clothing & Textiles', 10, 12, FALSE, NOW(), NOW()),
('Commerce', 10, 12, FALSE, NOW(), NOW()),
('Computer & IT', 10, 12, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET min_grade_level = LEAST(global_subjects.min_grade_level, EXCLUDED.min_grade_level), max_grade_level = GREATEST(global_subjects.max_grade_level, EXCLUDED.max_grade_level), is_core = EXCLUDED.is_core;

-- Insert JSS subjects (Grades 7-9)
INSERT INTO global_subjects (name, min_grade_level, max_grade_level, is_core, created_at, updated_at) VALUES
('Agriculture', 7, 9, TRUE, NOW(), NOW()),
('Arabic', 7, 9, FALSE, NOW(), NOW()),
('Basic Science', 7, 9, TRUE, NOW(), NOW()),
('Basic Technology', 7, 9, TRUE, NOW(), NOW()),
('Business Studies', 7, 9, FALSE, NOW(), NOW()),
('Christian Religious Studies', 7, 9, FALSE, NOW(), NOW()),
('Civic Education (Basic)', 7, 9, TRUE, NOW(), NOW()),
('Cultural And Creative Arts', 7, 9, FALSE, NOW(), NOW()),
('English Language', 7, 9, TRUE, NOW(), NOW()),
('Entrepreneurship', 7, 9, FALSE, NOW(), NOW()),
('French Language', 7, 9, FALSE, NOW(), NOW()),
('General Mathematics', 7, 9, TRUE, NOW(), NOW()),
('Hausa Language', 7, 9, FALSE, NOW(), NOW()),
('Home Economics', 7, 9, FALSE, NOW(), NOW()),
('Igbo Language', 7, 9, FALSE, NOW(), NOW()),
('Information Technology (IT)', 7, 9, TRUE, NOW(), NOW()),
('Islamic Studies', 7, 9, FALSE, NOW(), NOW()),
('Physical & Health Education', 7, 9, FALSE, NOW(), NOW()),
('Security Education', 7, 9, FALSE, NOW(), NOW()),
('Social Studies', 7, 9, TRUE, NOW(), NOW()),
('Yoruba Language', 7, 9, FALSE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET min_grade_level = LEAST(global_subjects.min_grade_level, EXCLUDED.min_grade_level), max_grade_level = GREATEST(global_subjects.max_grade_level, EXCLUDED.max_grade_level), is_core = EXCLUDED.is_core;

-- Insert Primary Lower subjects (Grades 1-3)
INSERT INTO global_subjects (name, min_grade_level, max_grade_level, is_core, created_at, updated_at) VALUES
('Arabic', 1, 3, FALSE, NOW(), NOW()),
('Basic Science', 1, 3, TRUE, NOW(), NOW()),
('Basic Technology', 1, 3, TRUE, NOW(), NOW()),
('Christian Religious Studies', 1, 3, FALSE, NOW(), NOW()),
('Civic Education (Basic)', 1, 3, TRUE, NOW(), NOW()),
('Cultural And Creative Arts', 1, 3, FALSE, NOW(), NOW()),
('English Language', 1, 3, TRUE, NOW(), NOW()),
('General Mathematics', 1, 3, TRUE, NOW(), NOW()),
('Hausa Language', 1, 3, FALSE, NOW(), NOW()),
('Igbo Language', 1, 3, FALSE, NOW(), NOW()),
('Information Technology (IT)', 1, 3, TRUE, NOW(), NOW()),
('Islamic Studies', 1, 3, FALSE, NOW(), NOW()),
('Physical & Health Education', 1, 3, FALSE, NOW(), NOW()),
('Security Education', 1, 3, FALSE, NOW(), NOW()),
('Social Studies', 1, 3, TRUE, NOW(), NOW()),
('Yoruba Language', 1, 3, FALSE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET min_grade_level = LEAST(global_subjects.min_grade_level, EXCLUDED.min_grade_level), max_grade_level = GREATEST(global_subjects.max_grade_level, EXCLUDED.max_grade_level), is_core = EXCLUDED.is_core;

-- Insert Primary Upper subjects (Grades 4-6)
INSERT INTO global_subjects (name, min_grade_level, max_grade_level, is_core, created_at, updated_at) VALUES
('Agriculture', 4, 6, TRUE, NOW(), NOW()),
('Arabic', 4, 6, FALSE, NOW(), NOW()),
('Basic Science', 4, 6, TRUE, NOW(), NOW()),
('Basic Technology', 4, 6, TRUE, NOW(), NOW()),
('Christian Religious Studies', 4, 6, FALSE, NOW(), NOW()),
('Civic Education (Basic)', 4, 6, TRUE, NOW(), NOW()),
('Cultural And Creative Arts', 4, 6, FALSE, NOW(), NOW()),
('English Language', 4, 6, TRUE, NOW(), NOW()),
('Entrepreneurship', 4, 6, FALSE, NOW(), NOW()),
('French Language', 4, 6, FALSE, NOW(), NOW()),
('General Mathematics', 4, 6, TRUE, NOW(), NOW()),
('Hausa Language', 4, 6, FALSE, NOW(), NOW()),
('Home Economics', 4, 6, FALSE, NOW(), NOW()),
('Igbo Language', 4, 6, FALSE, NOW(), NOW()),
('Information Technology (IT)', 4, 6, TRUE, NOW(), NOW()),
('Islamic Studies', 4, 6, FALSE, NOW(), NOW()),
('Physical & Health Education', 4, 6, FALSE, NOW(), NOW()),
('Security Education', 4, 6, FALSE, NOW(), NOW()),
('Social Studies', 4, 6, TRUE, NOW(), NOW()),
('Yoruba Language', 4, 6, FALSE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET min_grade_level = LEAST(global_subjects.min_grade_level, EXCLUDED.min_grade_level), max_grade_level = GREATEST(global_subjects.max_grade_level, EXCLUDED.max_grade_level), is_core = EXCLUDED.is_core;

-- Insert Pre-School subjects (Grades -3 to -2)
INSERT INTO global_subjects (name, min_grade_level, max_grade_level, is_core, created_at, updated_at) VALUES
('Handwriting', -3, -2, FALSE, NOW(), NOW()),
('Health Habits', -3, -2, FALSE, NOW(), NOW()),
('Literacy', -3, -2, FALSE, NOW(), NOW()),
('Numeracy', -3, -2, FALSE, NOW(), NOW()),
('Pre-Science', -3, -2, FALSE, NOW(), NOW()),
('Rest and Relaxation', -3, -2, FALSE, NOW(), NOW()),
('Social Habits', -3, -2, FALSE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET min_grade_level = LEAST(global_subjects.min_grade_level, EXCLUDED.min_grade_level), max_grade_level = GREATEST(global_subjects.max_grade_level, EXCLUDED.max_grade_level), is_core = EXCLUDED.is_core;

-- Insert Nursery subjects (Grades -1 to 0)
INSERT INTO global_subjects (name, min_grade_level, max_grade_level, is_core, created_at, updated_at) VALUES
('Basic Science and Technology', -1, 0, TRUE, NOW(), NOW()),
('Civic Education', -1, 0, TRUE, NOW(), NOW()),
('Creativity', -1, 0, FALSE, NOW(), NOW()),
('Handwriting', -1, 0, FALSE, NOW(), NOW()),
('Health Habits', -1, 0, FALSE, NOW(), NOW()),
('Literacy (Language Domain)', -1, 0, FALSE, NOW(), NOW()),
('Literacy (Letter Work)', -1, 0, FALSE, NOW(), NOW()),
('Numeracy', -1, 0, FALSE, NOW(), NOW()),
('Personal Development', -1, 0, FALSE, NOW(), NOW()),
('Physical and Health Education', -1, 0, FALSE, NOW(), NOW()),
('Social Habits', -1, 0, FALSE, NOW(), NOW()),
('Songs and Rhymes', -1, 0, FALSE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET min_grade_level = LEAST(global_subjects.min_grade_level, EXCLUDED.min_grade_level), max_grade_level = GREATEST(global_subjects.max_grade_level, EXCLUDED.max_grade_level), is_core = EXCLUDED.is_core;
