apply plugin: 'org.springframework.boot'
apply plugin: 'org.graalvm.buildtools.native'

graalvmNative {
    binaries {
        main {
            imageName = '4school'
            
            // Runtime Initializations (Consolidated from historic fixes)
            buildArgs.add('--initialize-at-run-time=okhttp3')
            buildArgs.add('--initialize-at-run-time=okio')
            buildArgs.add('--initialize-at-run-time=okhttp3.internal.http.RetryAndFollowUpInterceptor$Companion')
            buildArgs.add('--initialize-at-run-time=okhttp3.internal.http.RetryAndFollowUpInterceptor')
            buildArgs.add('--initialize-at-run-time=okhttp3.OkHttpClient')
            buildArgs.add('--initialize-at-run-time=okhttp3.internal.concurrent.TaskRunner$Companion')
            buildArgs.add('--initialize-at-run-time=okhttp3.internal.concurrent.TaskRunner')
            buildArgs.add('--initialize-at-run-time=okhttp3.internal.Platform')
            buildArgs.add('--initialize-at-run-time=com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std')
            
            // Build Time Initializations
            buildArgs.add('--initialize-at-build-time=org.slf4j')
            
            // General Native Image Args
            buildArgs.add('--no-fallback')
        }
    }
}

dependencies {
    implementation project(':core')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.dhatim:fastexcel:0.17.0'
    implementation 'net.logstash.logback:logstash-logback-encoder:8.0'
    implementation 'com.bucket4j:bucket4j-core:8.10.1'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
    
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

springBoot {
    mainClass = 'com.haneef._school.WebAppApplicationKt'
}

bootJar {
    archiveFileName = '4school-webapp.jar'
}
